services:
  lute-server:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    ports:
      - "4577:5279"
    volumes:
      - ./:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5279
    working_dir: /app
    command: dotnet watch run
